config/routes.rb
Applicable::Application.routes.draw do
  root to: "public#index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :students

  resources :students do
    resources :applications
  end

  match '/students' => 'student#index'

  match 'student/:id/archived', :as => 'archive_student', :to => 'student#archive'

  resources :student, :only => [:show], :as => :applicant

  match 'student/:id', :as => 'delete_student', :to => 'student#destroy', :via => :delete
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :employment_history, :employment_status, :application_reason,
                  :tech_background, :tech_story, :site_critique, :discovery,
                  :video, :program_selection, :seeking_job, :scholarship,
                  :location, :commitments, :awareness, :anything_else

  belongs_to :student

  after_create :send_completion_email, :send_new_applicant_email
  after_update :send_update_email, :send_admin_update_email

  private
  def send_completion_email
    StudentMailer.completion_email(student).deliver unless student.applications.blank?
  end

  def send_new_applicant_email
    StudentMailer.new_applicant_email(student).deliver unless student.applications.blank?
  end

  def send_update_email
    StudentMailer.application_update_email(student).deliver unless student.applications.blank?
  end

  def send_admin_update_email
    StudentMailer.applicant_has_updated_email(student).deliver unless student.applications.blank?
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :phone,
                  :date_of_birth, :twitter, :personal_url

  has_many :applications, :dependent => :destroy

  before_create :remove_at_sign_from_twitter

  def name
    first_name.nil? ? email : [first_name, last_name].join(" ")
  end

  def archive
    self.archived = true
    self.save!
  end

  private
  def remove_at_sign_from_twitter
    if self.twitter
      self.twitter.gsub(/^@/, '')
    end
  end
end

app/models/student_application.rb
class StudentApplication < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :phone,
                  :date_of_birth, :twitter, :personal_url,
                  :employment_history, :employment_status,
                  :application_reason, :tech_background,
                  :tech_story, :site_critique, :discovery,
                  :video, :program_selection, :seeking_job,
                  :scholarship, :location, :commitments,
                  :awareness, :anything_else, :user_id

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for resource
    if resource.is_a? Student
      student_url resource
    else
      admin_root_url
    end
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_student!

  def show
  end

  def new
    @application = student.applications.build
  end

  def create
    @application = student.applications.build params[:application]
    if @application.save
      flash[:notice] = "You have successfully completed your application"
      redirect_to student_url student
    else
     flash[:alert] = "There was a problem completing your application" 
     render 'applications/edit'
    end
  end

  def edit
  end

  def update
    if application.update_attributes params[:application]
      flash[:notice] = "You have successfully updated your application"
      redirect_to student_url student
    else
     flash[:alert] = "There was a problem updating your application" 
     render :back
    end
  end

  def destroy
    if application.destroy
      flash[:notice] = "Your application has been successfully deleted."
      redirect_to student_url student
    else
      flash[:alert] = "There was a problem deleteing your request"
      render 'students/show'
    end
  end

  helper_method :student
  def student
    @student ||= Student.find params[:student_id]
  end

  helper_method :application
  def application
    @application ||= student.applications.find params[:id] if student.applications.any?
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_student!

  def show
  end

  def edit
  end

  def update
    if student.update_attributes params[:student]
      flash[:notice] = 'You have successfully saved your info'
      redirect_to student_url
    else
      flash[:alert] = 'There was an error updating your info'
      render :back
    end
  end

  def destroy
    if student.destroy
      flash[:notice] = 'You have successfully deleted your account'
      redirect_to root_url
    else
      flash[:alert] = 'There was a problem deleting your account'
      render :back
    end
  end

  helper_method :student
  def student
    @student ||= Student.find(params[:id])
  end

  helper_method :application
  def application
    @application ||= student.applications.find params[:id] unless student.applications.empty?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/views/applications/_form.html.erb
<div class="row">
  <div class="twelve columns">
    <dl class="tabs">
      <dd class="active"><a href="#tab1">Employment Background</a></dd>
      <dd><a href="#tab2">Technology</a></dd>
      <dd><a href="#tab3">Finishing Up</a></dd>
    </dl>

    <%= simple_form_for [student, application] do |f|  %>
      <ul class="tabs-content">
        <%= render 'tab_one', :f => f %>

        <%= render 'tab_two', :f => f %>

        <%= render 'tab_three', :f => f %>
      </ul>
    <% end %>
  </div>
</div>

app/views/applications/_tab_one.html.erb
<li class="active" id="tab1Tab">
  <%= f.input :employment_history, :label => 'Employment History' %>
  <%= f.input :employment_status, :label => 'I am currently...',
                                  :collection => ['Self-employed', 'Employed',
                                    'Unemployed and looking for a job',
                                    'Unemployed but not looking',
                                    'A Student'],
                                  :as => :radio_buttons  %>

  <%= f.input :application_reason, :label => 'Why are you applying for the Nashville Software School?' %>
</li>

app/views/applications/_tab_three.html.erb
<li id="tab3Tab">
  <%= f.input :program_selection, :label => 'Which student cohort / program date are you applying for?',
              :collection => ['September 2013 for Web Development Bootcamp',
                    'TBD 2014 for Software Development Foundations (requires acceptance as an apprentice)',
                    'Either one - if I don\'t qualify as an apprentice I\'d like to enter the bootcamp in September'],
              :include_blank => false, :input_html => { :class => 'six columns' } %>

  <%= f.input :seeking_job, :label => 'Will you be looking for a job as a developer in the Nashville area after completion of your training and apprenticeship?',
              :collection => ['Yes, I will be seeking a job in Nashville', 'No, I will not be seeking a job in Nashville'],
              :as => :radio_buttons  %>

  <%= f.input :scholarship, :label => 'Are you a member of Nashville\'s minority, handicapped or economically disadvantaged community who would like to be considered for a sponsorship/scholarship?',
              :collection => ['Yes, if accepted I will need sponsorship in order to attend the summer 2012 program',
                              'No, I\'m prepared to pay the entire tuition fee on or before the first day of the program'],
              :as => :radio_buttons  %>

  <%= f.input :location, :label => 'Do you live in the Nashville area?',
              :collection => ['Yes','No but I will be moving there to attend Nashville Software School'],
              :as => :radio_buttons  %>

  <%= f.input :commitments, :label => 'Do you have commitments on the weekdays during Web Development Bootcamp?' %>
  <%= f.input :awareness, :label => 'How did you hear about Nashville Software School?' %>
  <%= f.input :anything_else, :label => 'Is there anything else that you would like us to know?' %>

<%- if student_signed_in? %>
  <%= f.submit 'Finish the Application', class: 'radius button twelve columns centered' %>
<%- else %>
  <%= link_to "Sign In", new_student_session_path %>
<% end %>
</li>

app/views/applications/_tab_two.html.erb
<li id="tab2Tab">
  <%= f.input :tech_background, :label => 'What is your background with computers/technology/programming?' %>
  <%= f.input :tech_story, :label => "The ideal candidate is someone who loves to solve problems or tinker and who doesn't easily give up.  Can you tell us a story that illustrates these qualities in you?" %>
  <%= f.input :site_critique, :label => 'What do you like and not like about our website?  What can we do better?' %>
  <%= f.input :discovery, :label => 'Please tell us something surprising or amusing that you have discovered.' %>
  <%= f.input :video, :label => 'Video link: It\'s not required but a short video gives you a chance to sell yourself to us in a way that text cannot.  To help make sure we like you, feel free to create a short video to support your application.  Put the link to the video here.' %>
</li>

app/views/applications/edit.html.erb
<p><%= link_to "<< back to your profile", student_path(student) %></p>
<h2>Your NSS Application:</h2>
<%= render 'form' %>

app/views/applications/new.html.erb
<p><%= link_to "<< back to your profile", student_path(student) %></p>
<h2>Your NSS Application:</h2>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

<!-- Uncomment to make IE8 render like IE7 -->
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

<!-- Set the viewport width to device width for mobile -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title><%= content_for?(:title) ? yield(:title) : "Applicable" %></title>

<!-- Included CSS Files -->
<%= stylesheet_link_tag    "application" %>

<!-- Included JS Files  -->
<%= javascript_include_tag "application" %>

<%= csrf_meta_tags %>
</head>
<body>
  <header>
  <div class="row">
      <nav class="top-bar">
        <ul>
          <li class="name">
          <h1><%= link_to "Applicable: An NSS Application App", :root %></h1>
          </li>
          <li class="toggle-topbar"><a href="#"></a></li>
        </ul>
        <section>
        <ul class="right">
          <%- if student_signed_in? %>
            <li class="signed-in-as">Signed in as <%= current_student.name %></li>
            <li><%= link_to "Sign Out", destroy_student_session_path, method: :delete %></li>
          <%- elsif admin_user_signed_in? %>
            <li><%= link_to "Back to Admin Panel", admin_dashboard_path %></li>
          <%- else %>
            <li><%= link_to "Sign Up", new_student_registration_path %></li>
            <li><%= link_to "Sign In", new_student_session_path %></li>
          <%- end %>
        </ul>
        </section>
      </nav>
  </div>
  </header>
  <div id="wrap">
    <div id="main">
      <div class="container row">
        <div class="twelve columns">
          <%= render "shared/flash" %>
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  <div class="push"></div>
  <footer>
  <div class="twelve columns">
    <div class="container row">
      <div class="left">
        <h5><%= link_to "Applicable: An NSS Application App", :root %></h5>
      </div>
      <div class="right admin-link button radius"><%= link_to "Admin", admin_dashboard_path %></div>
      <div class="right footer-info">
        <div id="copyright">&copy; 2012-<%= Time.now.year %></div>
      </div>
    </div>
  </div>
  </footer>
</body>
</html>

app/views/shared/_flash.html.erb
<% flash().each do |key, msg| %>
  <div id="flash" class="<%= key %> alert-box" data-prepend-to='wrap-content'>
    <%= msg.html_safe %>
    <a href="" class="close">&times;</a>
  </div>
<% end %>

app/views/student_applications/_form.html.erb
<dl class="tabs">
  <dd class="active"><a href="#simple1">Basic Information</a></dd>
  <dd><a href="#simple2">Employment Background</a></dd>
  <dd class="hide-for-small"><a href="#simple3">Technology</a></dd>
  <dd class="hide-for-small"><a href="#simple4">Finishing Up</a></dd>
</dl>
<%= simple_form_for(@student_application) do |f|  %>
<ul class="tabs-content">
  <li class="active" id="simple1Tab">
    <div class="row">
      <div class="six columns">
        <%= f.input :first_name, :label => 'First Name' %>
      </div>
      <div class="six columns">
        <%= f.input :last_name, :label => 'Last Name' %>
      </div>
    </div>
    <div class="row">
      <div class="six columns">
        <%= f.input :phone, :label => 'Phone' %>
      </div>
      <div class="six columns">
        <%= f.input :date_of_birth, :as => :date, :start_year => Date.today.year - 90,
                                      :end_year => Date.today.year - 12,
                                      :order => [:month, :day, :year] %>
      </div>
    </div>
    <div class="row">
      <div class="six columns">
        <%= f.input :twitter, :label => 'Twitter' %>
      </div>
      <div class="six columns">
        <%= f.input :personal_url, :label => 'Personal URL' %>
      </div>
    </div>
  </li>

  <li id="simple2Tab">
    <%= f.input :employment_history, :label => 'Employment History' %>
    <%= f.input :employment_status, :label => 'I am currently...', 
                                    :collection => ['Self-employed', 'Employed',
                                      'Unemployed and looking for a job',
                                      'Unemployed but not looking',
                                      'A Student'],
                                    :as => :radio_buttons  %>

    <%= f.input :application_reason, :label => 'Why are you applying for the Nashville Software School?' %>
  </li>

  <li id="simple3Tab">
    <%= f.input :tech_background, :label => 'What is your background with computers/technology/programming?' %>
    <%= f.input :tech_story, :label => "The ideal candidate is someone who loves to solve problems or tinker and who doesn't easily give up.  Can you tell us a story that illustrates these qualities in you?" %>
    <%= f.input :site_critique, :label => 'What do you like and not like about our website?  What can we do better?' %>
    <%= f.input :discovery, :label => 'Please tell us something surprising or amusing that you have discovered.' %>
    <%= f.input :video, :label => 'Video link: It\'s not required but a short video gives you a chance to sell yourself to us in a way that text cannot.  To help make sure we like you feel free to create a short video to support your application.  Put the link to the video here.' %>
  </li>

  <li id="simple4Tab">
    <%= f.input :program_selection, :label => 'Which student cohort / program date are you applying for?',
                :collection => ['January 2013 for Web Development Bootcamp',
                      'April 2013 for Software Development Foundations (requires acceptance as an apprentice)',
                      'Either one - if I don\'t qualify as an apprentice I\'d like to enter the bootcamp in January'],
                :as => :radio_buttons  %>

    <%= f.input :seeking_job, :label => 'Will you be looking for a job as a developer in the Nashville area after completion of your training and apprenticeship?',
                :collection => ['Yes', 'No'],
                :as => :radio_buttons  %>

    <%= f.input :scholarship, :label => 'Are you a member of Nashville\'s minority, handicapped or economically disadvantaged community who would like to be considered for a sponsorship/scholarship?',
                :collection => ['Yes, if accepted I will need sponsorship in order to attend the summer 2012 program',
                                'No, I\'m prepared to pay the entire tuition fee on or before the first day of the program'],
                :as => :radio_buttons  %>

    <%= f.input :location, :label => 'Do you live in the Nashville area?',
                :collection => ['Yes','No but I will be moving there to attend Nashville Software School'],
                :as => :radio_buttons  %>

    <%= f.input :commitments, :label => 'Do you have commitments on the weekdays during Web Development Bootcamp?' %>
    <%= f.input :awareness, :label => 'How did you hear about Nashville Software School?' %>
    <%= f.input :anything_else, :label => 'Is there anything else that you would like us to know?' %>

  <%- if user_signed_in? %>
    <%= f.submit submit_text, class: 'radius button twelve columns centered' %>
  <%- else %>
    <%= link_to "Sign In", new_user_session_path %>
  <% end %>
<% end %>
  </li>
</ul>

app/views/student_applications/show.html.erb
<h1>Review Your Application</h1>
<h2><%= @student_application.first_name %> <%= @student_application.last_name %></h2>
<h3><%= @student_application.user.email %></h3>
<%- [:phone,:date_of_birth, :twitter, :personal_url,
    :employment_history, :employment_status,
    :application_reason, :tech_background,
    :tech_story, :site_critique, :discovery,
    :video, :program_selection, :seeking_job,
    :scholarship, :location, :commitments,
    :awareness, :anything_else].each do |entry| %>
  <p>
    <strong><%= entry.to_s.humanize.capitalize %>:</strong>
    <%- if entry == :date_of_birth %>
      <%=  @student_application.send(entry).strftime("%B %-d, %Y") %>
    <%- else %>
      <%= @student_application.send(entry) %>
    <%- end %>
    <%= link_to "revise this answer", edit_student_application_path(@student_application) %>
  </p>
<%- end %>

app/views/students/_applications_table.html.erb
<section id="student-applications-table" class="panel">
  <% if student.applications.any? %>
    <h3 class="text-center">Your Applications</h3>
    <table class="large centered columns">
      <tr>
        <th>Program Selection</th>
        <th>Last Modified</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
      <% student.applications.select(&:persisted?).each do |application| %>
        <tr>
          <td><%= application.program_selection %></td>
          <td><%= application.updated_at.strftime("%B %-d, %Y") %></td>
          <td><%= link_to "Edit", edit_student_application_path(student, application) %></td>
          <td><%= link_to "Delete", student_application_path(student, application), :method => :delete, :confirm => "Are you sure? Deleting this application can not be undone." %></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</section>

app/views/students/_basic_info.html.erb
<section>
  <div class="row review">
    <div class="six columns">
      <h3><%= label_tag "Your Name" %></h3>
      <h3><%= student.name  if student.first_name %></h3>
    </div>
    <div class="six columns">
      <h3><%= label_tag "Your Email" %></h3>
      <h3><%= student.email %></h3>
    </div>
  </div>

  <div class="row review">
    <div class="six columns">
      <%= label_tag "Phone" %>
      <%= student.phone if student.phone %>
    </div>
    <div class="six columns">
      <%= label_tag "Date of Birth" %>
      <%= student.date_of_birth.strftime("%B %-d, %Y") if student.date_of_birth %>
    </div>
  </div>

  <div class="row review">
    <div class="six columns">
      <%= label_tag "Twitter Handle" %>
      <%= student.twitter if student.twitter %>
    </div>
    <div class="six columns">
      <%= label_tag "Personal URL" %>
      <%= link_to student.personal_url, url_with_protocol(student.personal_url) if student.personal_url %>
    </div>
  </div>
</section>

app/views/students/_form.html.erb
<div class="row">
  <div class="twelve columns">
    <%= simple_form_for(current_student, :url => student_path) do |f|  %>

      <div class="row">
        <div class="six columns">
          <%= f.input :first_name, :label => 'First Name' %>
        </div>
        <div class="six columns">
          <%= f.input :last_name, :label => 'Last Name' %>
        </div>
      </div>

      <div class="row">
        <div class="six columns">
          <%= f.input :phone, :label => 'Phone' %>
        </div>
        <div class="six columns">
          <%= f.input :date_of_birth, :as => :date, :start_year => Date.today.year - 90,
                                        :end_year => Date.today.year - 12,
                                        :order => [:month, :day, :year] %>
        </div>
      </div>

      <div class="row">
        <div class="six columns">
          <%= f.input :twitter, :label => 'Twitter' %>
        </div>
        <div class="six columns">
          <%= f.input :personal_url, :label => 'Personal URL' %>
        </div>
      </div>

      <% if student_signed_in? %>
        <%= f.submit 'Save Your Info', class: 'radius button twelve columns centered' %>
      <% else %>
        <%= link_to "Sign In", new_student_session_path %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/students/edit.html.erb
<h2>Edit Your Info</h2>
<%= render 'form' %>

app/views/students/show.html.erb
<h2>Review Your Info:</h2>
<%= render 'basic_info' %>

<%= render 'applications_table' %>

<div class="row">
</div>

<div class="row">
  <%= link_to "Start a New Application", new_student_application_path(student), class: "large radius button" %>
  <%= link_to "Edit This Info", edit_student_path(student), class: "large secondary radius button" %>
  <%= link_to "Delete Your Account", student_registration_path, :method => :delete, :confirm => 'Are you sure? This will delete your account and all associated applications.', :class => "large alert radius button"%>
</div>